version: '3.8'

services:
  obstore_api: 
    build: ./
    command: /app/obstore_api
    ports:      
      - 8090:8090
    depends_on:
      - db

  db: 
    restart: always
    image: mysql:latest
    volumes:
      - /data:/var/lib/mysql
    environment:
      - ROOT_PASSWORD=pmp1226
      - MYSQL_USER=pmp
      - MYSQL_PASSWORD=pmp1226
      - MYSQL_DATABASE=orderbuilds

    ports:
            - 3307:3306  